# Generated by Django 3.2.18 on 2023-08-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
