# Generated by Django 3.2.18 on 2023-08-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20230829_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.tipoproducto', verbose_name='Nombre'),
        ),
    ]
