# Generated by Django 3.2.18 on 2023-08-27 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20230510_0625'),
        ('solicitudes', '0002_rename_solicitudes_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto', verbose_name='Producto'),
        ),
    ]
