# Generated by Django 3.2.18 on 2023-08-29 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitud_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fechota',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
