# Generated by Django 3.2.18 on 2023-08-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitud_fechota'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptado')], default='P', max_length=20, verbose_name='Estado'),
        ),
    ]
