# Generated by Django 3.2.18 on 2023-06-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='correoelectronico',
            field=models.CharField(blank=True, default='Valor Default', max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razonsocial',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='regimenfiscal',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Regimen Fiscal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
