# Generated by Django 3.2.18 on 2023-06-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20230620_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
    ]
