# Generated by Django 3.2.18 on 2023-08-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='domicilio',
            field=models.CharField(max_length=60, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razonsocial',
            field=models.CharField(max_length=60, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='regimenfiscal',
            field=models.CharField(max_length=70, null=True, verbose_name='Regimen Fiscal'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
