# Generated by Django 3.2.18 on 2023-08-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20230830_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correoelectronico',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='E-mail'),
        ),
    ]
