# Generated by Django 3.2.18 on 2023-08-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(blank=True, default='Departamento default', max_length=100, unique=True, verbose_name='nombre'),
        ),
    ]
